version: "3.9"
services:
    server:
        build: 
            context: .
        ports:
            - "80:80"
        environment:
            - TZ=America/Sao_Paulo
        restart: always
        volumes:
            - .:/var/www
            - ./.docker/php:/usr/local/etc/php
            - ./.docker/apache2/sites-available:/etc/apache2/sites-available